# Generated by Django 3.0.7 on 2020-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('roll_no', models.IntegerField(default=0)),
                ('branch', models.CharField(default=0, max_length=40)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
