# Generated by Django 3.0.7 on 2020-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200901_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
